package agent_evolution

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type AgentCandidateGenerator struct {
	store       Store
	config      Config
	claudeDir   string
	opencodeDir string
}

func NewAgentCandidateGenerator(store Store, config Config, claudeDir, opencodeDir string) *AgentCandidateGenerator {
	return &AgentCandidateGenerator{
		store:       store,
		config:      config,
		claudeDir:   claudeDir,
		opencodeDir: opencodeDir,
	}
}

func (g *AgentCandidateGenerator) GenerateCandidates(ctx context.Context, opportunities []EvolutionOpportunity) ([]CandidateAgent, error) {
	candidates := make([]CandidateAgent, 0, len(opportunities))

	for _, opp := range opportunities {
		if opp.Confidence < g.config.MinConfidenceForCandidate {
			continue
		}

		candidateName := g.generateCandidateName(opp)
		existing, _ := g.store.GetCandidateByName(ctx, candidateName)
		if existing != nil && existing.Status != CandidateRejected {
			continue
		}

		candidate := g.createCandidate(opp)
		if err := g.store.SaveCandidate(ctx, &candidate); err != nil {
			continue
		}

		candidates = append(candidates, candidate)
	}

	return candidates, nil
}

func (g *AgentCandidateGenerator) createCandidate(opp EvolutionOpportunity) CandidateAgent {
	candidateName := g.generateCandidateName(opp)

	candidate := NewCandidateAgent(
		candidateName,
		opp.AgentName,
		opp.Specialization,
		opp.OpportunityType,
		opp.Reason,
		opp.Confidence,
	)

	candidate.PromptDiff = g.generatePromptDiff(opp)
	candidate.Evidence = opp.Evidence

	return candidate
}

func (g *AgentCandidateGenerator) generateCandidateName(opp EvolutionOpportunity) string {
	switch opp.OpportunityType {
	case OpportunitySpecialization:
		return g.generateSpecialistName(opp.AgentName, opp.Specialization)
	case OpportunityPromptImprove:
		return opp.AgentName + "-improved"
	case OpportunityDeprecation:
		return opp.AgentName + "-replacement"
	default:
		return opp.AgentName + "-v2"
	}
}

func (g *AgentCandidateGenerator) generateSpecialistName(baseAgent, specialization string) string {
	short := strings.ToLower(specialization)
	short = strings.ReplaceAll(short, "_", "-")
	short = strings.ReplaceAll(short, " ", "-")

	if len(short) > 20 {
		short = short[:20]
	}

	return baseAgent + "-" + short
}

func (g *AgentCandidateGenerator) generatePromptDiff(opp EvolutionOpportunity) PromptDiff {
	diff := PromptDiff{}

	switch opp.OpportunityType {
	case OpportunitySpecialization:
		diff.NewFocus = opp.Specialization
		diff.Additions = []string{
			"Specialize in " + opp.Specialization + " tasks",
			"Focus on " + opp.Specialization + " best practices and patterns",
		}

	case OpportunityPromptImprove:
		switch opp.Specialization {
		case "rework_reduction":
			diff.Additions = []string{
				"Verify your implementation against requirements before marking complete",
				"Run tests and lint checks before submission",
				"Double-check edge cases and error handling",
			}
		case "review_pass_improvement":
			diff.Additions = []string{
				"Ensure code follows project conventions",
				"Add appropriate tests for new code",
				"Review your changes against code review checklist",
			}
		default:
			diff.Additions = []string{
				"Pay special attention to: " + opp.Specialization,
				"Consider potential " + opp.Specialization + " issues",
			}
		}

	case OpportunityDeprecation:
		diff.Additions = []string{
			"This agent is deprecated due to low performance",
			"Consider using an alternative agent",
		}
	}

	return diff
}

func (g *AgentCandidateGenerator) GenerateAgentMarkdown(candidate CandidateAgent) (claudeContent, opencodeContent string) {
	claudeContent = g.generateClaudeAgentMarkdown(candidate)
	opencodeContent = g.generateOpenCodeAgentMarkdown(candidate)
	return
}

func (g *AgentCandidateGenerator) generateClaudeAgentMarkdown(candidate CandidateAgent) string {
	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("name: %s\n", candidate.AgentName))
	sb.WriteString(fmt.Sprintf("description: %q\n", g.generateDescription(candidate)))
	sb.WriteString("tools: Read, Grep, Glob, Edit, Write, Bash\n")
	sb.WriteString("---\n\n")

	sb.WriteString(fmt.Sprintf("# %s\n\n", g.formatTitle(candidate.AgentName)))

	sb.WriteString(fmt.Sprintf("This is a specialized agent derived from `%s`.\n\n", candidate.BaseAgent))

	sb.WriteString(fmt.Sprintf("**Specialization:** %s\n\n", candidate.Specialization))

	if len(candidate.PromptDiff.Additions) > 0 {
		sb.WriteString("**Additional Guidelines:**\n\n")
		for _, addition := range candidate.PromptDiff.Additions {
			sb.WriteString(fmt.Sprintf("- %s\n", addition))
		}
		sb.WriteString("\n")
	}

	if candidate.PromptDiff.NewFocus != "" {
		sb.WriteString(fmt.Sprintf("**Primary Focus:** %s\n\n", candidate.PromptDiff.NewFocus))
	}

	sb.WriteString(fmt.Sprintf("*(Generated by OpenClaw Agent Evolution - Confidence: %.2f)*\n", candidate.Confidence))

	return sb.String()
}

func (g *AgentCandidateGenerator) generateOpenCodeAgentMarkdown(candidate CandidateAgent) string {
	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("description: %s\n", g.generateDescription(candidate)))
	sb.WriteString("mode: subagent\n")
	sb.WriteString("tools:\n")
	sb.WriteString("  todo: false\n")
	sb.WriteString("---\n\n")

	sb.WriteString(fmt.Sprintf("# %s\n\n", g.formatTitle(candidate.AgentName)))

	sb.WriteString(fmt.Sprintf("This is a specialized agent derived from `%s`.\n\n", candidate.BaseAgent))

	sb.WriteString(fmt.Sprintf("**Specialization:** %s\n\n", candidate.Specialization))

	if len(candidate.PromptDiff.Additions) > 0 {
		sb.WriteString("**Additional Guidelines:**\n\n")
		for _, addition := range candidate.PromptDiff.Additions {
			sb.WriteString(fmt.Sprintf("- %s\n", addition))
		}
		sb.WriteString("\n")
	}

	if candidate.PromptDiff.NewFocus != "" {
		sb.WriteString(fmt.Sprintf("**Primary Focus:** %s\n\n", candidate.PromptDiff.NewFocus))
	}

	sb.WriteString(fmt.Sprintf("*(Generated by OpenClaw Agent Evolution - Confidence: %.2f)*\n", candidate.Confidence))

	return sb.String()
}

func (g *AgentCandidateGenerator) generateDescription(candidate CandidateAgent) string {
	switch candidate.OpportunityType {
	case OpportunitySpecialization:
		return fmt.Sprintf("Specialized %s agent for %s tasks", candidate.BaseAgent, candidate.Specialization)
	case OpportunityPromptImprove:
		return fmt.Sprintf("Improved %s agent with better quality checks", candidate.BaseAgent)
	case OpportunityDeprecation:
		return fmt.Sprintf("Replacement for deprecated %s agent", candidate.BaseAgent)
	default:
		return fmt.Sprintf("Evolved %s agent", candidate.BaseAgent)
	}
}

func (g *AgentCandidateGenerator) formatTitle(name string) string {
	parts := strings.Split(name, "-")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, " ")
}

func (g *AgentCandidateGenerator) WriteAgentFiles(candidate CandidateAgent) error {
	if g.claudeDir != "" {
		if err := os.MkdirAll(g.claudeDir, 0755); err != nil {
			return fmt.Errorf("create claude agents dir: %w", err)
		}
		claudeContent, _ := g.GenerateAgentMarkdown(candidate)
		claudePath := filepath.Join(g.claudeDir, candidate.AgentName+".md")
		if err := os.WriteFile(claudePath, []byte(claudeContent), 0644); err != nil {
			return fmt.Errorf("write claude agent: %w", err)
		}
	}

	if g.opencodeDir != "" {
		if err := os.MkdirAll(g.opencodeDir, 0755); err != nil {
			return fmt.Errorf("create opencode agents dir: %w", err)
		}
		_, opencodeContent := g.GenerateAgentMarkdown(candidate)
		opencodePath := filepath.Join(g.opencodeDir, candidate.AgentName+".md")
		if err := os.WriteFile(opencodePath, []byte(opencodeContent), 0644); err != nil {
			return fmt.Errorf("write opencode agent: %w", err)
		}
	}

	return nil
}

func (g *AgentCandidateGenerator) PromoteCandidate(ctx context.Context, candidateID string) error {
	candidate, err := g.store.GetCandidateByID(ctx, candidateID)
	if err != nil {
		return fmt.Errorf("get candidate: %w", err)
	}
	if candidate == nil {
		return fmt.Errorf("candidate not found")
	}

	if err := g.WriteAgentFiles(*candidate); err != nil {
		return fmt.Errorf("write agent files: %w", err)
	}

	candidate.Status = CandidatePromoted
	if err := g.store.SaveCandidate(ctx, candidate); err != nil {
		return fmt.Errorf("update candidate status: %w", err)
	}

	return nil
}
