package wiki_engine_test

import (
	"errors"
	"fmt"
	"testing"

	"github.com/MartinNevlaha/stratus-v2/db"
	"github.com/MartinNevlaha/stratus-v2/internal/insight/wiki_engine"
)

// linkerErrStore is a minimal WikiStore whose SaveLink always returns an error.
// All other methods panic — they are not expected to be called by the Linker.
type linkerErrStore struct {
	saveErr error
}

func (s *linkerErrStore) SavePage(p *db.WikiPage) error { panic("not called") }
func (s *linkerErrStore) UpdatePage(p *db.WikiPage) error { panic("not called") }
func (s *linkerErrStore) GetPage(id string) (*db.WikiPage, error) { panic("not called") }
func (s *linkerErrStore) ListPages(f db.WikiPageFilters) ([]db.WikiPage, int, error) {
	panic("not called")
}
func (s *linkerErrStore) SearchPages(query string, pageType string, limit int) ([]db.WikiPage, error) {
	panic("not called")
}
func (s *linkerErrStore) DeletePage(id string) error { panic("not called") }
func (s *linkerErrStore) UpdatePageStaleness(id string, score float64) error {
	panic("not called")
}
func (s *linkerErrStore) SaveLink(l *db.WikiLink) error { return s.saveErr }
func (s *linkerErrStore) ListLinksFrom(pageID string) ([]db.WikiLink, error) {
	panic("not called")
}
func (s *linkerErrStore) ListLinksTo(pageID string) ([]db.WikiLink, error) { panic("not called") }
func (s *linkerErrStore) DeleteLinks(pageID string) error                   { panic("not called") }
func (s *linkerErrStore) GetGraph(pageType string, limit int) ([]db.WikiPage, []db.WikiLink, error) {
	panic("not called")
}
func (s *linkerErrStore) SaveRef(r *db.WikiPageRef) error { panic("not called") }
func (s *linkerErrStore) ListRefs(pageID string) ([]db.WikiPageRef, error) { panic("not called") }
func (s *linkerErrStore) DeleteRefs(pageID string) error                    { panic("not called") }

// --- helpers ---

func newLinker(t *testing.T) *wiki_engine.Linker {
	t.Helper()
	return wiki_engine.NewLinker(newMockStore())
}

func linkerPage(id, title, content string) *db.WikiPage {
	return &db.WikiPage{ID: id, Title: title, Content: content, PageType: "entity"}
}

// --- DetectCrossReferences ---

func TestDetectCrossReferences_FindsTitleMentions(t *testing.T) {
	linker := newLinker(t)

	// pageA's content mentions pageB's title "Tokens".
	pageA := linkerPage("id-a", "Authentication", fmt.Sprintf("We use %s to secure the API.", "Tokens"))
	pageB := linkerPage("id-b", "Tokens", "Tokens are generated by the auth service.")

	links := linker.DetectCrossReferences(pageA, []db.WikiPage{*pageA, *pageB})

	if len(links) != 1 {
		t.Fatalf("expected 1 link, got %d", len(links))
	}
	l := links[0]
	if l.FromPageID != "id-a" {
		t.Errorf("FromPageID: want id-a, got %q", l.FromPageID)
	}
	if l.ToPageID != "id-b" {
		t.Errorf("ToPageID: want id-b, got %q", l.ToPageID)
	}
	if l.LinkType != "related" {
		t.Errorf("LinkType: want related, got %q", l.LinkType)
	}
	if l.Strength != 0.5 {
		t.Errorf("Strength: want 0.5, got %f", l.Strength)
	}
}

func TestDetectCrossReferences_CaseInsensitive(t *testing.T) {
	linker := newLinker(t)

	// pageA content mentions "gateway" (lowercase); pageB title is "GATEWAY" (uppercase).
	pageA := linkerPage("id-a", "Router", "The gateway handles all routing decisions.")
	pageB := linkerPage("id-b", "GATEWAY", "GATEWAY routes incoming requests.")

	links := linker.DetectCrossReferences(pageA, []db.WikiPage{*pageA, *pageB})

	if len(links) != 1 {
		t.Fatalf("expected 1 link from case-insensitive match, got %d", len(links))
	}
	if links[0].ToPageID != "id-b" {
		t.Errorf("ToPageID: want id-b, got %q", links[0].ToPageID)
	}
}

func TestDetectCrossReferences_SkipsSelfReference(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "Cache", "Cache invalidation is a hard problem in distributed systems.")

	links := linker.DetectCrossReferences(pageA, []db.WikiPage{*pageA})

	if len(links) != 0 {
		t.Errorf("expected 0 links (no self-reference), got %d", len(links))
	}
}

func TestDetectCrossReferences_NoMatches(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "Database", "Stores persistent data in tables.")
	pageB := linkerPage("id-b", "Zephyr", "A completely unrelated concept with no mention of the other.")

	links := linker.DetectCrossReferences(pageA, []db.WikiPage{*pageA, *pageB})

	if len(links) != 0 {
		t.Errorf("expected 0 links for unrelated content, got %d", len(links))
	}
}

// --- DetectSharedSourceLinks ---

func TestDetectSharedSourceLinks_TwoShared(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "Page A", "content a")
	pageB := linkerPage("id-b", "Page B", "content b")

	refsA := []db.WikiPageRef{
		{PageID: "id-a", SourceType: "event", SourceID: "evt-1"},
		{PageID: "id-a", SourceType: "event", SourceID: "evt-2"},
		{PageID: "id-a", SourceType: "artifact", SourceID: "art-1"},
	}
	refsB := []db.WikiPageRef{
		{PageID: "id-b", SourceType: "event", SourceID: "evt-1"},
		{PageID: "id-b", SourceType: "event", SourceID: "evt-2"},
	}

	link := linker.DetectSharedSourceLinks(pageA, refsA, pageB, refsB)

	if link == nil {
		t.Fatal("expected a link for 2 shared sources, got nil")
	}
	if link.FromPageID != "id-a" {
		t.Errorf("FromPageID: want id-a, got %q", link.FromPageID)
	}
	if link.ToPageID != "id-b" {
		t.Errorf("ToPageID: want id-b, got %q", link.ToPageID)
	}
	if link.LinkType != "related" {
		t.Errorf("LinkType: want related, got %q", link.LinkType)
	}
	// 2 shared * 0.2 = 0.4, not capped.
	const wantStrength = 0.4
	if link.Strength != wantStrength {
		t.Errorf("Strength: want %f, got %f", wantStrength, link.Strength)
	}
}

func TestDetectSharedSourceLinks_OneShared(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "A", "content")
	pageB := linkerPage("id-b", "B", "content")

	refsA := []db.WikiPageRef{{PageID: "id-a", SourceType: "event", SourceID: "evt-1"}}
	refsB := []db.WikiPageRef{{PageID: "id-b", SourceType: "event", SourceID: "evt-1"}}

	link := linker.DetectSharedSourceLinks(pageA, refsA, pageB, refsB)

	if link != nil {
		t.Errorf("expected nil for 1 shared source (below threshold), got %+v", link)
	}
}

func TestDetectSharedSourceLinks_ZeroShared(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "A", "content")
	pageB := linkerPage("id-b", "B", "content")

	refsA := []db.WikiPageRef{{PageID: "id-a", SourceType: "event", SourceID: "evt-1"}}
	refsB := []db.WikiPageRef{{PageID: "id-b", SourceType: "event", SourceID: "evt-99"}}

	link := linker.DetectSharedSourceLinks(pageA, refsA, pageB, refsB)

	if link != nil {
		t.Errorf("expected nil for 0 shared sources, got %+v", link)
	}
}

// --- FindContradictions ---

func TestFindContradictions_SamePrefixDifferentContent(t *testing.T) {
	linker := newLinker(t)

	// Same title (same first 3 words), but different content -> different hash.
	pageA := linkerPage("id-a", "Order Service API", "Handles order creation and payment flow via REST.")
	pageB := linkerPage("id-b", "Order Service API", "Manages order lifecycle including cancellation via gRPC.")

	pages := []db.WikiPage{*pageA, *pageB}
	links := linker.FindContradictions(pages)

	if len(links) == 0 {
		t.Fatal("expected at least one contradiction link, got none")
	}
	l := links[0]
	if l.LinkType != "contradicts" {
		t.Errorf("LinkType: want contradicts, got %q", l.LinkType)
	}
	if l.Strength != 0.7 {
		t.Errorf("Strength: want 0.7, got %f", l.Strength)
	}
	pairOK := (l.FromPageID == "id-a" && l.ToPageID == "id-b") ||
		(l.FromPageID == "id-b" && l.ToPageID == "id-a")
	if !pairOK {
		t.Errorf("unexpected link pair: %q -> %q", l.FromPageID, l.ToPageID)
	}
}

func TestFindContradictions_NoContradictions(t *testing.T) {
	linker := newLinker(t)

	pageA := linkerPage("id-a", "Authentication Service Overview", "Handles user login.")
	pageB := linkerPage("id-b", "Payment Gateway Integration", "Handles billing and invoices.")

	links := linker.FindContradictions([]db.WikiPage{*pageA, *pageB})

	if len(links) != 0 {
		t.Errorf("expected 0 contradiction links, got %d", len(links))
	}
}

// --- SaveDetectedLinks ---

func TestSaveDetectedLinks_Success(t *testing.T) {
	store := newMockStore()
	linker := wiki_engine.NewLinker(store)

	links := []db.WikiLink{
		{FromPageID: "id-a", ToPageID: "id-b", LinkType: "related", Strength: 0.5},
		{FromPageID: "id-b", ToPageID: "id-c", LinkType: "contradicts", Strength: 0.7},
	}

	count, err := linker.SaveDetectedLinks(links)
	if err != nil {
		t.Fatalf("SaveDetectedLinks: %v", err)
	}
	if count != 2 {
		t.Errorf("count: want 2, got %d", count)
	}
	// Verify links were sent to the store.
	fromALinks, _ := store.ListLinksFrom("id-a")
	_ = fromALinks // mockStore.ListLinksFrom returns nil; we check via ListLinksTo.
	toB, _ := store.ListLinksTo("id-b")
	if len(toB) != 1 {
		t.Errorf("expected 1 link pointing to id-b, got %d", len(toB))
	}
}

func TestSaveDetectedLinks_StoreError_ReturnsError(t *testing.T) {
	store := &linkerErrStore{saveErr: errors.New("db unavailable")}
	linker := wiki_engine.NewLinker(store)

	links := []db.WikiLink{
		{FromPageID: "id-a", ToPageID: "id-b", LinkType: "related", Strength: 0.5},
	}

	count, err := linker.SaveDetectedLinks(links)
	if err == nil {
		t.Fatal("expected error from store failure, got nil")
	}
	if count != 0 {
		t.Errorf("count: want 0 when all saves fail, got %d", count)
	}
}
